name: Debug Build

on:
  push:
    branches:
      - 'master'
      - 'AppManager-*'
    paths-ignore:
      - 'fastlane/**'
      - 'scripts/**'
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'fastlane/**'
      - 'scripts/**'
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew packageDebugUniversalApk
      - name: Rename the APK file
        run: mv ./app/build/outputs/apk_from_bundle/debug/app-debug-universal.apk ./lol.apk
      - name: Store generated APK file
        uses: actions/upload-artifact@v3
        with:
          name: lol
          path: ./lol.apk
      
